services:
  - type: web
    name: scraper-api
    runtime: docker
    plan: free
    buildCommand: docker build -t scraper-api .
    startCommand: docker run -p $PORT:3000 scraper-api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    buildFilter:
      paths:
        - src/**
        - package.json
        - pnpm-lock.yaml
        - Dockerfile
    autoDeploy: true 